# Change these first
owner: aaronsentell # Your GitHub organization or username, where this repository lives
repo: my-status-page # The name of this repository

# Setting to run once a year, because I'm controlling this with cron-job
workflow-schedules:
  uptime: "0 0 1 * *"

sites:
  - name: Pour Decisions
    url: https://pour.madebyaaron.app
  - name: Round on Me
    url: https://round.madebyaaron.app
  - name: The Pollening
    url: https://pollen.madebyaaron.app
  - name: SPF or RIP
    url: https://burn.madebyaaron.app
  - name: Project Website (madebyaaron.app)
    url: https://madebyaaron.app
  - name: Personal Website (aaronsentell.com)
    url: https://aaronsentell.com
  - name: Referral Site
    url: $REFERRAL_SITE
  - name: Civic Site
    url: $CONTACT_REPS

status-website:
  # Your custom domain is set here
  cname: status.madebyaaron.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Made by Aaron Status Page
  introTitle: "**App Status**"
  introMessage: Real-time monitoring and status page for my personal websites and projects.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Discord notifications configuration
notifications:
  - type: discord
    webhookUrl: $DISCORD_WEBHOOK_URL
